"""empty message

Revision ID: eba622ed026
Revises: 459265bcd414
Create Date: 2014-09-22 23:35:46.597000

"""

# revision identifiers, used by Alembic.
revision = 'eba622ed026'
down_revision = '459265bcd414'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_id', sa.String(length=60), nullable=True))
    op.add_column('device', sa.Column('registration_id', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'registration_id')
    op.drop_column('device', 'device_id')
    ### end Alembic commands ###
